---
name: website
'on':
  pull_request:
  push:
    branches:
      - main
      - test
#  schedule:
#    - cron: "0 2 * * *"
env:
  DOCKERHUB_USERNAME: "edennolan2021"
  IMAGE_NAME: "website"
  IMAGE_TAG: "latest"
  CONTAINER_PORT: "80"
  EXPOSED_PORT: "80"

jobs:
  build:
    name: BUILD DOCKER IMAGE
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Build Image
        run: | 
          docker build -t ${DOCKERHUB_USERNAME}/$IMAGE_NAME:$IMAGE_TAG .
          docker save ${DOCKERHUB_USERNAME}/$IMAGE_NAME:$IMAGE_TAG > $IMAGE_NAME
          echo "IMAGE_NAME=website" >> $GITHUB_ENV
      - name: Cache artefact
        uses: actions/cache@v3
        with:
          key: image
          path: ${{ env.IMAGE_NAME }}
          

  run-and-test:
    name: RUN AND TEST CONTAINER
    needs: build
    runs-on: ubuntu-latest
    steps:  
      - name: Download workspace from job build
        uses: actions/cache@v3
        with:
          key: image
          path: ${{ env.IMAGE_NAME }}
      - name: Run container based on builded image
        run: |
          docker load < $IMAGE_NAME
          docker run --name $IMAGE_NAME -d -p ${EXPOSED_PORT}:${CONTAINER_PORT} -e PORT=$CONTAINER_PORT ${DOCKERHUB_USERNAME}/$IMAGE_NAME:$IMAGE_TAG
          sleep 5

      - name: Test image.
        run: curl "http://localhost:${EXPORT_PORT}" | grep -i "Dimension"

      - name: Clean Container
        run: |
          docker stop $IMAGE_NAME
          docker rm $IMAGE_NAME

  push:
    name: PUSH IMAGE ON DOCKERHUB
    needs: run-and-test
    runs-on: ubuntu-latest
    steps:    
      - name: Download workspace from job build
        uses: actions/cache@v3
        with:
          key: image
          path: ${{ env.IMAGE_NAME }}
      - name: Login and Push Image on docker hub
        run: |
          docker load < $IMAGE_NAME
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push ${DOCKERHUB_USERNAME}/$IMAGE_NAME:$IMAGE_TAG          
        
  deploy:
    name: DEPLOY APPLICATION
    needs: push
    runs-on: ubuntu-latest
    steps:  
      - name: Check out the codebase.
        uses: actions/checkout@v2              
      - name: Install and configure Heroku CLI
        run: | 
          sudo apt install nodejs
          echo "STAGING=${DOCKERHUB_USERNAME}-staging" >> $GITHUB_ENV
          echo "PRODUCTION=${DOCKERHUB_USERNAME}-production" >> $GITHUB_ENV
      
      - name: Deploy Staging
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: | 
          heroku container:login
          heroku create ${STAGING}  || echo "project already exist"
          heroku container:push -a ${STAGING} web
          heroku container:release -a ${STAGING} web    
      
      - name: Deploy PRODUCTION
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: | 
          heroku container:login
          heroku create ${PRODUCTION}  || echo "project already exist"
          heroku container:push -a ${PRODUCTION} web
          heroku container:release -a ${PRODUCTION} web    
